### ISSUE TITLE
[pytest-bdd] Screenshot on fail isn't captured. no 'page' in funcargs

### ISSUE THREAD

**Issue by sqandrew** [microsoft/playwright-pytest#57] opened 2021-06-07 15:59 UTC
Updated [test repo](https://github.com/sqandrew/pytestbdd-pw-test) to fail.
Added pytest_runtest_makereport to conftest.py

while debug there was no 'page' in funcargs [here](https://github.com/sqandrew/pytestbdd-pw-test/blob/main/conftest.py#L12)
![image](https://user-images.githubusercontent.com/11583548/121051273-010acd00-c7c2-11eb-805f-102468effae4.png)

Please advise,
Thanks in advance

**Comment by mxschmitt** [comment] 2021-06-07 16:07
I tried it with the latest version but was not able to reproduce it with your example. Could you install the latest version via ` pip install pytest-playwright==0.1.2` to make sure it got installed correctly and not the cached one was used?

**Comment by sqandrew** [comment] 2021-06-07 17:47
were you able to make a screenshot with this test?

I uninstalled pytest-playwright, than made pip install pytest-playwright==0.1.2. without changes - `and "page" in item.funcargs` is not true. (Python 3.9.0)

**Comment by mxschmitt** [comment] 2021-06-07 19:17
Yes it worked for me. I made the following changes:

```diff
diff --git a/features/test.feature b/features/test.feature
index cac51d2..77daad8 100644
--- a/features/test.feature
+++ b/features/test.feature
@@ -2,3 +2,4 @@ Feature: Demo feature
   
   Scenario: Demo scenario
     Given I open browser
+    Then I make a screenshot
\ No newline at end of file
diff --git a/step_definition/demo.py b/step_definition/demo.py
index 93eb8d4..16ff183 100644
--- a/step_definition/demo.py
+++ b/step_definition/demo.py
@@ -4,4 +4,7 @@ from pytest_bdd import scenarios, given, when, then
 @given("I open browser")
 def step_impl(page):
     page.goto("https://example.com")
-    assert False
+
+@then("I make a screenshot")
+def step_impl(page):
+    page.screenshot(path="foo.png")

```

**Comment by sqandrew** [comment] 2021-06-08 03:35
Let me be more precise.

What works OK for me: 
unconditional screenshot capture. 
For example, using page.screenshot(path="foo.png") in a regular step, as it is in your changes above.



What doesn't work:
[Screenshot on test failure](https://github.com/microsoft/playwright-pytest#screenshot-on-test-failure)
[The condition](https://github.com/sqandrew/pytestbdd-pw-test/blob/main/conftest.py#L12) never becomes true, because there is no 'page' in funcargs.

**Comment by mxschmitt** [comment] 2021-06-08 09:51
Oh gotcha! Yeah this is since they use classes probably internally, thats why you need such a hacky solution:

```diff
diff --git a/conftest.py b/conftest.py
index d3f58e1..8deceda 100644
--- a/conftest.py
+++ b/conftest.py
@@ -9,8 +9,8 @@ from pathlib import Path
 
 def pytest_runtest_makereport(item, call) -> None:
     if call.when == "call":
-        if call.excinfo is not None and "page" in item.funcargs:
-            page = item.funcargs["page"]
+        if "page" in item.funcargs["request"]._fixture_defs:
+            page = item.funcargs["request"]._fixture_defs["page"].cached_result[0]
             screenshot_dir = Path(".playwright-screenshots")
             screenshot_dir.mkdir(exist_ok=True)
             page.screenshot(path=str(screenshot_dir / f"{slugify(item.nodeid)}.png"))
\ No newline at end of file

```

Stay tuned for Playwright version 1.12 which gets released in a few days. It includes a tracing feature with which its not required anymore to have videos/screenshots on failure. With them after and before every step a snapshot is made which you can view locally. And everything is contained in a single zip file.

**Comment by sqandrew** [comment] 2021-06-08 10:32
amazing! thanks for the solution and forecast!

**Closed** 2021-06-08 11:23 UTC
Labels: triaging
