### ISSUE TITLE
[Feature]: Make pytest-playwright available on conda

### ISSUE THREAD

**Issue by marimeireles** [microsoft/playwright-pytest#127] opened 2022-07-29 20:31 UTC
Hey all, 
Thanks for the work on playwright.
I'm encountering this issue when trying to run it with both python 3.9 and 3.10.
I wonder if it's some interaction with conda packages solvers?

Here's the full error:

```
(pyscript)  ✘  ~/dev/pyscript/pyscriptjs   main ±  pip install pytest-playwright
Collecting pytest-playwright
  Using cached pytest_playwright-0.3.0-py3-none-any.whl (10 kB)
ERROR: Could not find a version that satisfies the requirement playwright>=1.18 (from pytest-playwright) (from versions: none)
ERROR: No matching distribution found for playwright>=1.18 (from pytest-playwright)
```

If I try to specify playwright versions or just download any playwright, I get:

```
(pyscript)  ✘  ~/dev/pyscript/pyscriptjs   main ±  pip install playwright

ERROR: Could not find a version that satisfies the requirement playwright (from versions: none)
ERROR: No matching distribution found for playwright
```

Which python: `/Users/user/miniconda3/envs/pyscript/bin/python`

If you're interested I can create a recipe for conda-forge and maintain it.

Cheers.

**Comment by aspenboy** [comment] 2022-07-29 20:42
Nothing rings a bell to me, as for me it works - however maybe try to create new, clean virtual env?

**Comment by mxschmitt** [comment] 2022-07-29 22:45
Which operating system are you using?

**Comment by marimeireles** [comment] 2022-07-29 22:51
Well, the pypi website says it's OS independent, where can I see which are the supported OSs?
And I'm using an M1, osx.
Thanks for the replies!

**Comment by marimeireles** [comment] 2022-07-29 22:51
I tried with a clean environment... But I'll try again starting with `playwright` and see if it solves my issue, thanks!

**Comment by marimeireles** [comment] 2022-07-29 23:05
K, this did the trick for me.
I had to run `playwright install` by the end of it, but seems like everything is working fine.
I do believe it's some conflict between different solvers, because I have to use both `pip` and `conda`.
I know microsoft have their own conda channel, but is it possible to also host a version of `pytest-playwright` on `conda-forge`?
Thanks for the help here! (Feel free to close it)

**Comment by mxschmitt** [comment] 2022-07-30 06:37
Ah, pytest-playwright is not on conda yet. Let me do it next week.

Only Playwright is for now.

macos m1 is definitely supported!

**Comment by mxschmitt** [comment] 2022-08-01 08:38
Internal note: Was looking into supporting it, since playwright is published under the microsoft conda channel, pytest-playwright also needs to be published there, which requires manually pushing logic.

Marking it as p3 for now since its more effort compared to conda-forge.

**Comment by marimeireles** [comment] 2022-08-03 13:15
Hey @mxschmitt, thanks for the reply :)
I don't understand what you mean with more effort?
I did a lot of `conda-forge` work in the past and I'm available to help if you need! Cheers and thank you.

**Comment by mxschmitt** [comment] 2022-08-03 13:29
> Hey @mxschmitt, thanks for the reply :)
> I don't understand what you mean with more effort?
> I did a lot of `conda-forge` work in the past and I'm available to help if you need! Cheers and thank you.

I think the problem is that Playwright is under the Microsoft channel and forge is an own channel.

https://anaconda.org/Microsoft/playwright

**Comment by marimeireles** [comment] 2022-08-03 15:10
Hum, I see.
Yeah that's true, it's not possible to have `requirements` coming from outside `conda-forge`.
Thanks!

**Comment by maximlt** [comment] 2022-08-10 12:14
I concur that it would be nice to have this package available on conda (whatever the channel!), and that is is possible to automate publishing packages to a conda channel so that it's not a manual step part of the release process.

**Closed** 2023-08-09 13:43 UTC
Labels: p3-collecting-feedback
