### ISSUE TITLE
truncate_file_name() didn't work when I configured --output

### ISSUE THREAD

**Issue by floraachy** [microsoft/playwright-pytest#231] opened 2024-07-10 03:46 UTC
I set tracing,screenshot and video opened.

**Comment by floraachy** [comment] 2024-07-10 05:41
In pytest, I have configured options for taking screenshots, recording videos, and tracing。
[pytest]
addopts =
    --tracing=on
    --screenshot=on
    --video=on

also， I have configured options "--output" with my own directory. For example: --output=outputs/tracing

When I run test,  if the test case name is too long, it will be unable to take screenshots and record videos.

testcase name:  test_login_user_no_phone[chromium-网页登录，正确用户名和密码登录成功，弹窗后提示未绑定手机号码]

I checked `pytest"_playwright.py`, It will runcates the length of the screenshot file name. But it seems doesn't work.


# pytest"_playwright.py
def _build_artifact_test_folder(
    pytestconfig: Any, request: pytest.FixtureRequest, folder_or_file_name: str
) -> str:
    output_dir = pytestconfig.getoption("--output")
    return os.path.join(
        output_dir,
        truncate_file_name(slugify(request.node.nodeid)),
        truncate_file_name(folder_or_file_name),
    )


def truncate_file_name(file_name: str) -> str:
    if len(file_name) < 256:
        return file_name
    return f"{file_name[:100]}-{hashlib.sha256(file_name.encode()).hexdigest()[:7]}-{file_name[-100:]}"

**Comment by mxschmitt** [comment] 2024-07-10 07:21
>  it will be unable to take screenshots and record videos.

do you have an error which you receive?

**Comment by floraachy** [comment] 2024-07-10 09:13
> > it will be unable to take screenshots and record videos.
> 
> Can you share the error which you receive?

only one case, it didn‘t generate pictures and video., this is the error:

![image](https://github.com/microsoft/playwright-pytest/assets/62091502/44161eca-f042-49e6-ba9b-a1a8e0a14938)



When I changed the testcase name, long name to short name. It run success and genertate picures and videos successfully.
![f0fad1b99e256b05b9790f87d846020](https://github.com/microsoft/playwright-pytest/assets/62091502/3d5735ab-3b11-4d2f-ae48-a27d717e3e49)

**Comment by mxschmitt** [comment] 2024-07-12 12:16
Could you help us creating a minimal reproduction for it? I tried to execute the following ,but for me it was working as expected:

```python
import pytest

testdata = [
    ("网页登录，正确用户名和密码登录成功，弹窗后提示未绑定手机号码弹窗后提示未绑定手机号码弹窗后提示未绑定手机号码]机号码弹窗绑定手机号码弹窗后提示未绑定手机号码]机号码弹窗后提绑定手机号码弹窗后提示未绑定手机号码]机号码弹窗后提绑定手机号码弹窗后提示未绑定手机号码]机号码弹窗后提后提示未绑定手机号码弹窗后提示未绑定手机号码]机号码弹窗后提示未绑定手机号码弹窗后提示未绑定手机号码]机号码弹窗后提示未绑定手机号码弹窗后提示未绑定手机号码]机号码弹窗后提示未绑定手机号码弹窗后提示未绑定手机号码]"),
]


@pytest.mark.parametrize("name", testdata)
def test_timedistance_v0(name, page):
    print(name)

```

I was running it with `--video=on --screenshot=on --tracing=on`

**Comment by floraachy** [comment] 2024-07-15 00:40
> ```python
> 网页登录，正确用户名和密码登录成功，弹窗后提示未绑定手机号码
> ```

# test_gitlink.py
```
import allure
from playwright.sync_api import Page, expect
import pytest


@allure.feature("GitLink")
@pytest.mark.parametrize('case',
                         [{"title": "网页登录，正确用户名和密码登录成功，弹窗后提示未绑定手机号码", "name": "GitLink"}],
                         ids=lambda x: x["title"])
def test_gitlink(page: Page, case):
    with allure.step("访问GitLink"):
        page.goto("https://www.gitlink.org.cn/explore")

    with allure.step("断言：访问成功"):
        expect(page).to_have_url("https://www.gitlink.org.cn/explore")
        assert "GitLink" == case["name"]
```

# main.py
```
import pytest
import os

if __name__ == '__main__':
import pytest

if __name__ == '__main__':
    pytest.main(["--browser=chromium", "--headed"])
```

# pytest.ini
```
[pytest]
addopts =
    --tracing=on
    --screenshot=on
    --video=on
    --output=results
```

When I run `main.py`, ERROR happened:
![image](https://github.com/user-attachments/assets/b838622a-610b-429b-93a8-e939b91119fc)

**Comment by floraachy** [comment] 2024-07-16 00:51
> ```shell
> os.pathconf('/', 'PC_NAME_MAX')
> ```
My system version: Windows 11 专业版 - 23H2 - 22631.3880
Python version=3.9.5
![image](https://github.com/user-attachments/assets/35073b55-0b13-4374-afcb-3e62c6bb68fe)

**Comment by mxschmitt** [comment] 2024-07-16 12:10
I see, while looking at the error message, I stumped across [this post](https://stackoverflow.com/a/76452218/6512681) - we recommend to have this setting enabled, could you try enabling this? The issue is that the whole path length reaches this limit, so it would be hard from our side to take care of that, since the parent path could be already very long.

**Comment by floraachy** [comment] 2024-07-17 01:27
> I see, while looking at the error message, I stumped across [this post](https://stackoverflow.com/a/76452218/6512681) - we recommend to have this setting enabled, could you try enabling this? The issue is that the whole path length reaches this limit, so it would be hard from our side to take care of that, since the parent path could be already very long.

I changed `Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem LongPathsEnabled`  from 0 to 1, no error happen and the folder generated successfully.


Could we limit  the maximum length of directory names through code?
I thought this method: `truncate_file_name`, was used to limit the length of directory . 
I still can't understand why it didn't work.

![1721179357692](https://github.com/user-attachments/assets/dc7cc601-5575-4345-a6be-fbac503620bb)

**Comment by floraachy** [comment] 2024-07-17 02:48
> I see, while looking at the error message, I stumped across [this post](https://stackoverflow.com/a/76452218/6512681) - we recommend to have this setting enabled, could you try enabling this? The issue is that the whole path length reaches this limit, so it would be hard from our side to take care of that, since the parent path could be already very long.

I made a little change, and It solved my problem for now. (I don't want adjust my system：`Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem LongPathsEnabled` )。

![563d6ccfdd3984a6f44f06f478ede4e](https://github.com/user-attachments/assets/ca753f7c-9a6c-4ad7-bd7b-97390404d752)

**Comment by mxschmitt** [comment] 2024-12-18 16:18
This issue has two viable solutions:

1. Enable long path support in Windows by setting `LongPathsEnabled=1` in 
`Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem` (new Windows 11 default)

2. Use shorter test case names to stay under Windows' default path length limits

The `truncate_file_name()` function is working as designed, but Windows' default path length restrictions can still cause issues with the full artifact paths. Since this is a Windows-specific limitation that can be addressed through system settings or test naming conventions, I suggest we close this issue.

For users encountering similar issues, please either:
- Enable long path support in Windows (recommended)
- Use shorter test names
- Configure a shorter base output directory path

Closing as the functionality is working as expected and workarounds are available.

**Closed by mxschmitt** 2024-12-18 16:18 UTC
